export const dealFields = [
  {
    name: "deal_name",
    label: "Deal Name",
    type: "text",
    required: true,
    placeholder: "Enter deal name",
  },
  {
    name: "lead_id",
    label: "Associated Lead",
    type: "select",
    placeholder: "Select associated lead",
  },
  {
    name: "company_id",
    label: "Company",
    type: "select",
    disabled: true,
    placeholder: "Select company",
  },
  {
    name: "deal_stage",
    label: "Deal Stage",
    type: "select",
    placeholder: "Select deal stage",
    options: [
      "Presentation Scheduled",
      "Qualified to Buy",
      "Contract Sent",
      "Appointment Scheduled",
      "Decision Maker Bought-In",
      "Closed Won",
      "Closed Lost",
    ],
  },
  {
    name: "amount",
    label: "Amount",
    type: "number",
    required: true,
    placeholder: "Enter deal amount",
  },
  {
    name: "owner_id",
    label: "Deal Owner",
    type: "select",
    placeholder: "Select deal owner",
  },
  {
    name: "close_date",
    label: "Close Date",
    type: "date",
    required: true,
    placeholder: "Select close date",
  },
  {
    name: "priority",
    label: "Priority",
    type: "select",
    placeholder: "Select priority",
    options: ["Low", "Medium", "High", "Critical"],
  },
];